package repositories

// Import "dumbmerch/models", "gorm.io/gorm"

// Declare UserRepository interface here ...

// Declare repository struct here ...

// Create RepositoryUser function here ...

// Create FindUsers method here ...

// Create GetUser method here ...