package handlers

// Declare Todos Struct here ...

// Declare Global Variable here ...

// Create FindTodos Function here ...

// Create GetTodo Function here ...

// Create CreateTodo Function here ...

// Create UpdateTodo Function here ...

// Create DeleteTodo Function here ...